
[api]
port = 3000
host = "127.0.0.1" # by default API server is accessible from localhost only
maxSize = "5M" # maximum size of an attachment when submitting or uploading messages

[dbs]
# redis connection
redis = "redis://h:p248509087dec16dd1aca9516a6080af35da6dbb80f6e31134e1f9a6504c610b4@ec2-54-211-163-228.compute-1.amazonaws.com:6489"

[log]
level = "trace"